DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	SEXO ENUM ('M', 'F'),
	IDADE int,
	CIDADE VARCHAR(20)
);

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (1, "ANDERSON", "M", 17, "PALHOÇA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (2, "CESAR", "M", 21, "SAO JOSE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (3, "DANIEL", "M", 19, "PALHOÇA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (4, "DIEGO", "M", 19, "BLUMENAU");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (5, "EDUARDO", "M", 20, " ");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (6, "GABRIEL", "M", 19, "TUBARAO");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (7, "JOAO", "M", 18, "SAO JOSE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (8, "LEONARDO", "M", 20, " ");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (9, "LUCAS", "M", 20, "BLUMENAU");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (10, "PRISCILA", "F", 19, "PALHOÇA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (11, "RENATA", "F", 21, "TUBARÃO");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (12, "MARIA", "F", 22, "BLUMENAU");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (13, "TANIA", "F", 19, "SAO JOSE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (14, "CARLOS", "M", 22, "TUBARAO");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (15, "JOSE", "M", 19, "PALHOÇA");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (16, "MARISA", "F", 19, " ");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (17, "AMANDA", "F", 20, " ");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (18, "JOANA", "F", 19, " ");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (19, "ALICE", "F", 21, "SAO JOSE");

INSERT INTO ALUNO(IDALUNO, NOME, SEXO, IDADE, CIDADE)
VALUES (20, "TADEU", "M",18, "TUBARAO");
