DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO(
	IDALUNOS INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(20) NOT NULL
	, SEXO CHAR(1)
	, IDADE INT
	, CIDADE VARCHAR(20)
    , PRIMARY KEY (IDALUNO)
);

INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('SOFIA', 17, 'F','PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MATHEUS', 20, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RUAN', 18, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 21, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PEDRO', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EMILI', 17, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JULIA', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PRISCILA', 22, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RENATA', 23, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CAMILA', 21, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TANIA', 17, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RAFAEL', 18, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MAISA', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TIAGO', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JESSICA', 21, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MANU', 20, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LEONARDO', 18, 'M', 'TUBARAO');

SELECT * FROM ALUNO WHERE SEXO = 'M';
SELECT * FROM ALUNO WHERE IDADE = 19;
SELECT * FROM ALUNO WHERE NOME LIKE 'D%';
SELECT * FROM ALUNO WHERE IDADE BETWEEN 20 AND 22;
SELECT * FROM ALUNO WHERE CIDADE IS NULL;
SELECT * FROM ALUNO WHERE CIDADE = 'BLUMENAU';
SELECT * FROM ALUNO WHERE IDADE <>18;
SELECT * FROM ALUNO WHERE NOME LIKE '%RI%';
SELECT * FROM ALUNO WHERE SEXO = 'M' AND IDADE < 20;
SELECT * FROM ALUNO WHERE (SEXO = 'F' AND IDADE > 20) OR (SEXO = 'M' AND IDADE > 17);
SELECT * FROM ALUNO WHERE NOME LIKE "%A%" AND NOME LIKE "%R%";
SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';
SELECT IDALUNO FROM ALUNO WHERE CIDADE = "BLUMENAU";
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE<18;
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE >=15 AND IDADE <= 18 AND CIDADE <> "PALHOCA";
SELECT CIDADE FROM ALUNO WHERE CIDADE <> "NULL"; 
SELECT NOME FROM ALUNO WHERE (IDADE = 18 AND CIDADE = "PALHOCA") OR (IDADE = 17 AND CIDADE = "SAO JOSE");
SELECT NOME FROM ALUNO WHERE SEXO = 'M' AND CIDADE = "TUBARAO" AND IDADE >=18 AND IDADE <= 25;
SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;
SELECT * FROM ALUNO ORDER BY IDADE DESC, NOME ASC; 
SELECT * FROM ALUNO ORDER BY SEXO, NOME;



